### ISSUE TITLE
[liveproxy-server][error] No playable streams found on this URL [NEW ERROR/ISSUE]

### ISSUE THREAD

**Issue by CyberPoison** [back-to/liveproxy#19]
Hi, everyone.

Hi have some issue on my liveproxy Server on my local network, well it has worked fine for month maybe for a entire year,
But now i'm getting this error 

```
[liveproxy-server][info] Plugin path /root/.config/streamlink/plugins does not exist or is not a directory!
[liveproxy-server][info] Found matching plugin twitch for URL https://www.twitch.tv/gotaga
[liveproxy-server][error] No playable streams found on this URL: https://www.twitch.tv/gotaga
```

the streamer was live at that moment and not able to grab the m3u the same for ESL_CSGO and all the others i have.

so now this is all my data liveproxy data info
```
[liveproxy-main][info] For LiveProxy support visit https://github.com/back-to/liveproxy
[liveproxy-main][debug] OS:         Linux-4.15.0-121-generic-x86_64-with-Ubuntu-18.04-bionic
[liveproxy-main][debug] Python:     2.7.17
[liveproxy-main][debug] LiveProxy:  1.0.0
[liveproxy-main][debug] Streamlink: 1.4.1
[liveproxy-main][debug] Requests:   2.23.0
[liveproxy-main][info] Starting server: 0.0.0.0 on port 53422
```

pip 20.3.3 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)

not sure how, but if there is a way to update the streamlink package using this method it will be nice to tell us how.

My installation method.
```
git clone --depth 1 --branch 1.0.0  git://github.com/back-to/liveproxy.git liveproxy
 cd liveproxy
 python setup.py install
 ```

using this method it uses the 2.7 path of python but with ``` pip install . ``` it install on the 3.6 path i guess the 2.7 is deprecated i read some message when i deployed a other app btw. 

if i install using pip i get this.

```
  File "/usr/local/bin/liveproxy", line 5, in <module>
    from liveproxy.main import main
  File "/usr/local/lib/python3.6/dist-packages/liveproxy/main.py", line 15, in <module>
    from .argparser import parser
  File "/usr/local/lib/python3.6/dist-packages/liveproxy/argparser.py", line 8, in <module>
    from .constants import FILE_OUTPUT_LIST
  File "/usr/local/lib/python3.6/dist-packages/liveproxy/constants.py", line 3, in <module>
    from streamlink.compat import is_py2, is_win32
ImportError: cannot import name 'is_py2'
```
because i guess this is using python3.6 and your project only works on 2.7 

the actual master branch is not working because it talks about MacOS things and etc... so i don't used this one.

Resuming: if you tell me how can i update the Streamlink it will be nice "using the installation above git......", and also how i can unintall the allready installed package using the method above, and how can i set the env to use python2.7 when installing pip packages btw i will not use pip i will install install it by ``` python setup.py install ```

Kind Regards

**Comment by CyberPoison** [comment]
Bad news i have edited the setup.py to install the latest streamlink but unfortunately it doesn't work. liveproxy give issues on api.py 

Edit:
I have installed it on a Container and i have able to update to 1.7.0 Streamlink but still that issue.

```
[liveproxy-server][info] Plugin path /root/.config/streamlink/plugins does not exist or is not a directory!
[liveproxy-server][info] Found matching plugin twitch for URL https://www.twitch.tv/gotaga
[liveproxy-server][error] No playable streams found on this URL: https://www.twitch.tv/gotaga
```

 maybe a issue with streamlink not sure what and where i need to repord but well i also can see than you are a contributor on Streamlink repo, if you can fix it and tell me how can i update from 1.4.1 to the latest streamlink version to put this functional it will be nice, or if this is a issue with liveproxy just post here thanks for all your god job :)

**Comment by CyberPoison** [comment]
Same thing on a container with @janrk alpine image

```
[liveproxy-server][info] Found matching plugin twitch for URL https://www.twitch.tv/esl_csgo
[liveproxy-server][error] No playable streams found on this URL: https://www.twitch.tv/esl_csgo
```

**Comment by back-to** [comment]
you will need `Streamlink 2.0.0`

---

as of `Liveproxy 1.0.0`, it will probably not work.
You will need to use the dev version from github `LiveProxy 2.0.0.dev0`
https://liveproxy.github.io/install.html#source-code

Because of the **python 2.7** drop from **Streamlink**,
I changed Liveproxy to make it easier maintainable for issues like this.

But it is currently not fully ready for a new release on pip,
there are still some small changes needed.

**Comment by CyberPoison** [comment]
I have managed to put it working but now i have very few lags on the video when playing some streams from twitch.

latest dev branch from liveproxy and 2.0.0 on streamlink

tested on two diferent containers 

EDIT: Not related with liveproxy/streamlink so not issue related with this because other streams works nicely so i will try the same streamers tomorrow to check
